# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PW', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=15)),
            ],
        ),
    ]
