# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PW', '0003_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagen', models.FileField(blank=True, upload_to='/')),
                ('Genero', models.CharField(max_length=10)),
                ('Titulo', models.CharField(max_length=15)),
                ('Autor', models.CharField(max_length=20)),
                ('Precio', models.CharField(max_length=8)),
            ],
        ),
    ]
