# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PW', '0004_disco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disco',
            old_name='Imagen',
            new_name='imagen',
        ),
    ]
